cart/urls.py
from django.urls import path, include
from cart import views
urlpatterns = [
    path('main/',views.mycart,name='mycart'),
    path('main/addproduct/',views.addproduct,name='add'),
    path('main/setCartItem/',views.setCartItemAmount,name='set'),
    path('main/delCartItem/',views.delCartItem,name='del'),
    path('main/trueDelCartItem/',views.trueDelCartItem,name='trueDel'),
    path('main/reCartItem/',views.reCartItem,name='re'),

]

dangdang/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('DangDang/', include(('index.urls', 'dd'))),
    path('DangDang/login/', include(('login.urls', 'log'))),
    path('DangDang/register/', include(('register.urls', 'reg'))),
    path('DangDang/cart/', include(('cart.urls', 'cart'))),
    path('DangDang/indent/',include(('indent.urls','ind'))),
    path('DangDang/admin/complie/',include(('admin_app.urls','adm'))),
]

indent/urls.py
from django.urls import path, include
from indent import views

urlpatterns = [
    path('main/',views.getindent,name='get'),
    path('main/ok/',views.retindent,name='ret'),
    path('main/logic/',views.indent_logic,name='logic'),
    path('main/set/address/',views.setaddress,name='set'),
    path('main/backto/cart/',views.backToCart,name='back')

]

indent/models.py
from django.db import models
from login.models import User
from index.models import Product,AddProduct

# Create your models here.
class Address(models.Model):
    '''描述一个用户的地址'''
    consignee= models.CharField(max_length=50)
    detailAddress = models.CharField(max_length=200)
    postalcode = models.CharField(max_length=10)
    telephone = models.CharField(max_length=12,null=True)
    mobilephone = models.CharField(max_length=15,null=True)
    userid = models.ForeignKey(to=User,on_delete=models.SET_NULL,null=True)
    class Meta:
        db_table = 'd_address'

class Orders(models.Model):
    '''描述一个订单'''
    orderNumber = models.CharField(max_length=30)
    dateInProduct = models.DateTimeField()
    status = models.CharField(max_length=10)
    freight = models.FloatField()
    #总金额
    expenditure = models.FloatField(0)
    customer = models.ForeignKey(to=User,on_delete=models.SET_NULL,null=True)
    address = models.ForeignKey(to=Address,on_delete=models.SET_NULL,null = True)
    class Meta:
        db_table = 'd_orders'

class OrderItems(models.Model):
    '''描述一个订单项'''
    productName = models.CharField(max_length=100)
    price = models.FloatField()
    amount = models.IntegerField()
    subtotal = models.FloatField()
    orderid = models.ForeignKey(to=Orders,on_delete=models.CASCADE,null=True)
    class Meta:
        db_table = 'd_orderitems'

indent/views.py
import random

import time
import traceback

from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render,redirect,HttpResponse
from login.models import User
from indent.models import Address,Orders,OrderItems
from index.models import Product,AddProduct

from cart.car import Cart,CartItem

# Create your views here.
from django.urls import reverse

def getsalt():
    '''订单盐'''
    l='0987654321'
    t='qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLLZXCVBNM'
    salt_body=''.join(random.sample(l,8)).replace(" ","")
    salt_head=''.join(random.sample(t,4)).replace(" ","")
    salt = salt_head + salt_body + str(int(time.time()))
    return salt

def freight(cuthand):
    '''计算运费'''
    try:
        if cuthand.getTotalMoney() > 100:
            return 0
        else:
            return 10
    except TypeError:
        return 1

def getindent(request):
    '''访问订单页'''
    print('this is get indent')
    #获取登录gid
    gid = request.session.get('gid')
    #获取nickname
    nickname = request.COOKIES.get('user')
    if gid and nickname:
        gid=int(gid)
        #获取购物车对象
        cuthand = request.session.get('cuthand')
        #查询该用户的地址信息
        address = Address.objects.filter(userid=gid)
        print('地址信息',address)
        #获取运费
        fght = freight(cuthand)
        if fght == 1:
            return redirect('cart:mycart')
        #总金额
        totalprice = fght+cuthand.getTotalMoney()
        print(nickname,gid)
        print(cuthand,fght)
        # 查询该用户的地址信息
        address = Address.objects.filter(userid=gid)
        print(address)
        return render(request, 'indent/indent.html', {'nickname': nickname, 'cuthand': cuthand, 'totalprice': totalprice, 'address': address})
    else:
        url = reverse('log:login')+'?returnurl='+reverse('ind:get')
        return HttpResponseRedirect(url)

def indent_logic(request):
    print('this is indent logic')
    #获取订单项session.如果存在删除
    order = request.session.get('order')
    if order:
        del request.session['order']
    #获取登录gid
    gid = int(request.session.get('gid'))
    #查询用户
    guser=User.objects.get(pk=gid)
    #获取购物车对象
    cuthand = request.session.get('cuthand')
    #获取form表单对象
        #获取地址信息
    adrs_flag = int(request.POST.get('address'))
    print(adrs_flag)
    try:
        with transaction.atomic():
            if adrs_flag == -1:
                #获取收货人
                consignee = request.POST.get('ship_man')
                #获取详细地址
                dtas = request.POST.get('detailAddress')
                #获取邮编
                ptle = request.POST.get('postalcode')
                #获取手机号
                mph = request.POST.get('mobilephone')
                #获取固定电话
                tph = request.POST.get('telephone')
                print('收货人：',consignee,'详细地址：',dtas,'邮政编码：',ptle,'手机号：',mph,'固定电话：',tph,'用户id：',gid)
                #创建地址对象,判断地址对象存不存在
                address = Address(consignee=consignee,detailAddress=dtas,postalcode=ptle,telephone=tph,mobilephone=mph,userid=guser)
                address.save()
            else:
                address = Address.objects.filter(id=adrs_flag,userid=gid)[0]
    except:
        traceback.print_exc()
    try:
        with transaction.atomic():
            #获取订单盐
            salt = getsalt()
            #获取当前时间
            dip = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime())
            #获取运费
            fght = freight(cuthand)
            #获取总金额
            totalprice = fght+cuthand.getTotalMoney()
            #创建订单对象
            print('订单号：',salt,'订单时间：',dip,'运费：',fght,'总金额：',totalprice)
            newOrders = Orders(orderNumber=salt,dateInProduct=dip,status=0,freight=fght,expenditure=totalprice,customer=guser,address=address)
            #持久化
            newOrders.save()
            #存入session
            request.session['order']=newOrders
    except:
        traceback.print_exc()
    try:
        with transaction.atomic():
            cartFlag=[]
            for one in cuthand.cartItems:
                cartFlag.append(one)
                productName = one.product.name
                price= one.product.addproduct.dangdang_price
                amount=one.amount
                subtotal=one.getSubTotal()
                print('商品：',productName,'价格：',price,'数量：',amount,'小计：',subtotal)
                newOrderItems=OrderItems(productName=productName,price=price,amount=amount,subtotal=subtotal,orderid=newOrders)
                newOrderItems.save()
                #更新商品销售数据
                aproduct = AddProduct.objects.get(product_id__id=one.product.id)
                aproduct.sales = aproduct.sales+amount
                aproduct.save()
                print('sales:',aproduct.sales)
            print('cartFlag:',cartFlag)
            request.session['cartFlag']=cartFlag
    except:
        traceback.print_exc()

    return HttpResponse(1)

def retindent(request):
    '''访问订单已生产界面'''
    print('this is return indent')
    #获取nickname
    nickname = request.COOKIES.get('user')
    #获取session中的order
    order = request.session.get('order')
    #获取购物车
    cuthand = request.session.get('cuthand')
    #将购物车中的订单项去除,获取cartFlag
    cartFlag = request.session.get('cartFlag')
    print('删除前：',cuthand.cartItems,cuthand.uncartItems)
    if cartFlag:
        for one in cartFlag:
            #将购物车中的订单项移入删除模块
            cuthand.subCartItem(one.product)
        print('删除中：',cuthand.cartItems,cuthand.uncartItems)
        for one in cartFlag:
            #删除购物车中删除模块中的订单项
            cuthand.delCartItem(one.product)
        print('删除后：',cuthand.cartItems,cuthand.uncartItems)
    # 获取移出商品的记录，并将移出商品添加到购物车中
    delproduct = request.session.get('delproduct')
    if delproduct:
        for one in delproduct:
            cuthand. reCartItem(one)
        del request.session['delproduct']
    print('检查购物车：',cuthand.cartItems,cuthand.uncartItems)
    request.session['ctuhand']=cuthand
    return render(request,'indent/indent ok.html',{'order':order,'nickname':nickname})

def setaddress(request):
    '''异步刷新地址栏'''
    print('this is set address')
    #获取地址id
    adid = request.GET.get('adid')
    #查询地址对象
    adrs = Address.objects.filter(pk=adid)
    def mydefault(a):
        if isinstance(a,Address):
            a ={'id':a.id,'consignee':a.consignee,'detailAddress':a.detailAddress,'postalcode':a.postalcode,'telephone':a.telephone,'mobilephone':a.mobilephone}
        return a
    if adrs:
        address=adrs[0]
        return JsonResponse({'address':address},json_dumps_params={'default':mydefault})
    else:
        return HttpResponse(-1)

def backToCart(request):
    print('this is back to cart')
    #判断是否存在移出商品记录,没有则创建新的记录list
    delproduct = request.session.get('delproduct')
    if not delproduct:
        delproduct = []
    #获取商品id
    id = int(request.GET.get('id'))
    #查询商品
    product = Product.objects.get(pk=id)
    #获取购物车对象
    cuthand = request.session.get('cuthand')
    #将要删除的商品从当前购物车的cartItems移入uncartItems,保留移出商品的记录
    cuthand.subCartItem(product)
    #保存记录,并存入session
    delproduct.append(product)
    request.session['delproduct']=delproduct
    #保存新的购物车
    request.session['cuthand']=cuthand
    #返回购物车对象
    # def mydefault(a):
    #     if isinstance(a, Cart):
    #         a = {'getTotalMoney': a.getTotalMoney(), 'getSaveMoney': a.getSaveMoney(),'cartItems':a.cartItems}
    #     if isinstance(a, CartItem):
    #         a = {'amount': a.amount, 'product': a.product, 'getSubTotal': a.getSubTotal()}
    #     if isinstance(a, Product):
    #         a = {'id': a.id,'publishing_house':a.publishing_house,'addproduct':a.addproduct}
    #     if isinstance(a, AddProduct):
    #         a = {'dangdang_prcie': a.dangdang_price}
    #     return a
    # return JsonResponse({'cuthand':cuthand},json_dumps_params={"default":mydefault})
    return HttpResponse(1)

templates/indent/indent ok.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>百知教育</title>
    <script src="{% static 'js/jquery_1.8.js' %}"></script>
    <script src="{% static 'js/jquery_cookie.js' %}"></script>
	<link rel="shortcut icon" href="{% static 'images/favicon.ico?v=20160901' %}" type="image/x-icon">
    <link href="{% static 'css/shopping_cart_new.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/footer_150526.css' %}" rel="stylesheet" type="text/css" />
</head>

<body style="padding-bottom:82px">

<link href="{% static 'css/header_960_150611.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/pagetop2015_0827.js' %}" charset="gb2312" type="text/javascript"></script>

<div id="hd">
<div id="tools">
<div class="tools">
    <div class="ddnewhead_operate" dd_name="顶链接">
        
        <div class="ddnewhead_welcome" display="none;">
            <span id="nickname">
                {% if nickname %}
                    <span class="hi">欢迎光临当当，</span>
                    <a href="javascript:void(0)" class="login_link">{{ nickname }}</a>
                    <a href="{% url 'log:out' %}?returnurl={% url 'cart:mycart' %}" style="margin-left: 5px;">[退出]</a>
                 {% endif %}
            </span>
            <div class="tel_pop" style="display:none" id="__ddnav_sjdd" onmouseover="showgaoji('a_phonechannel','__ddnav_sjdd');" onmouseout="hideotherchannel('a_phonechannel','__ddnav_sjdd');">
                <a target="_blank" href="http://t.dangdang.com/20130220_ydmr" class="title"><i class="icon_tel"></i>手机当当</a><i class="title_shadow"></i>
                <ul class="tel_pop_box">
                    <li><a href="http://t.dangdang.com/20130220_ydmr" dd_name="手机二维码"><span>当当手机客户端</span><img src="http://img3.ddimg.cn/00363/doc/erweima2.png"><span class="text">随手查订单<br>随时享优惠</span></a></li>
                </ul>
            </div>
        </div>
        <div class="new_head_znx" id="znx_content" style="display:none;"></div>
    </div>
</div>
</div>
<div id="header_end"></div>
</div>
<form action="http://search.dangdang.com/search.aspx" id="bootpagetopSearch" name="bootpagetopSearch" method="GET"></form>
<script type="text/javascript">var nick_num = 0;initHeaderOperate();</script><script type="text/javascript" src="http://orderb.dangdang.com/queryunpaid?callback=Unpaid_Data"></script>
		<div class="shoppingcart_wrapper" id="ad_cpt_11850"><div><a href="http://a.dangdang.com/tjump.php?q=ddo84XQOf357bOs8tXGg5%2F%2F0oVoDImt3DFWsMqu7ZMSVsfUMeOQJueASNiMLjq%2FdrXMLCKnVfyKEahteAh1ih%2ByKYrKGzhvL20LVbDzObRambBA0YPpivy5hR5foQ4Rt%2BTB" target="_blank" rel="nofollow"><img src="http://img62.ddimg.cn/2017/1/11/2017011111344969879.jpg"></a></div></div>
<div class="logo_line">
    <div class="w960">
        <div class="shopping_procedure02 shopping_procedure "><span>我的购物车</span><span>填写订单</span><span class="current">完成订单</span></div>
        <div class="logo"><a href="#"><img src="{% static 'images/bz_logo_car.jpg' %}" alt=""></a></div>
    </div>
</div>
<div class="checkout-wrap">
    <div class="indent_con">
        <div class="order-box orderEnd-box">
            <div class="orderEnd-box-top">
                <div class="topbar">
                </div>
                <h2>
                    <span id="spanOrderTip" class="text">感谢您提交订单，我们将及时为您处理！</span>
                </h2>
                     <div class="" style="margin-left: 402px;margin-top: -35px;margin-bottom: 100px">
                         <div><a href="{% url 'dd:index' %}" style="font-size: 18px;margin-bottom: 10px">去看看其他商品</a></div>
                         <div style="margin-top: 20px"><span><em id="em" style="color: red">6</em>秒后自动返回购物车</span></div>
                     </div>
                            <script>
                                var n=6;
                                var em = document.getElementById('em');
                                var timer = setInterval(function(){
                                    em.innerText=String(--n);
                                    console.log(n);
                                    if(!n) {
                                        console.log('bingo');
                                        clearInterval(timer);
                                        location.href = '{% url 'cart:mycart' %}';
                                    }
                                },1000);
                            </script>


            </div>
            <div class="orderEnd-box-cont">
                <div id="NotPeerPayOrderList" class="pay-instead-order">


                </div>
                <div class="pay-normal" id="order_list">
                    <div class="item-order">
                        <h3>订单：
                            <a href="http://order.dangdang.com/orderdetails.aspx?orderid=34673930343" target="_blank">
                            <span class="number">{{ order.orderNumber }}</span>
                            </a>
                        </h3>
                        <div class="cont minh-40">
                            <table cellpadding="0" cellspacing="0">
                                <tbody>
                                    <tr>
                                        <td width="53"></td>
                                        <td>
                                            <span class="popup-Details spd">{{ order.orderitems_set.all|length }}件商品
                                                <i class="icon icon-details"></i>
                                                <div class="popup-wrap popup-orderEnd-detail" style="right:-288px; top:12px;display:none;">
                                                    <div class="popup-cont">
                                                        <p>
                                                            <span class="span-w230">活着（余华经典著作）</span>
                                                            <strong class="color-orange">x1</strong>
                                                        </p>
                                                    </div>
                                                </div>
                                            </span>
                                            <div class="popup-wrap popup-orderEnd-detail" style="right:-288px; top:12px;display:none;">
                                                <div class="popup-cont">
                                                    <p>
                                                        <span class="span-w230">活着（余华经典著作）</span>
                                                        <strong class="color-orange">x1</strong>
                                                    </p>
                                                </div>
                                            </div>
                                            <span>送给</span>
                                            <span class="popup-Details spd">{{ order.address.consignee }}
                                                <i class="icon icon-details"></i>
                                                <div class="popup-wrap popup-orderEnd-detail" style="right:-288px; top:12px;display:none;">
                                                    <div class="popup-cont">
                                                        <p>{{ order.address.detailAddress }}{{ order.address.postalcode }}</p>
                                                        <p>电话：{{ order.address.mobilephone }}</p>
                                                        <p>固定电话：{{ order.address.telephone }}</p>
                                                    </div>
                                                </div>
                                            </span>
                                            <span>配送方为</span>
                                            <span>当当网</span>
                                        </td>
                                    </tr>
                                    <tr class="hackie6">
                                        <td>&nbsp;</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="order-price">
                            <p>支付金额：
                                <span class="price-d">¥{{ order.expenditure|floatformat:2 }}</span>
                            </p>
                            <p class="p-hdfk">货到付款</p>
                        </div>
                        <div class="itemtext">
                            <span class="color-red">安全提醒：</span>当当平台及销售商不会以订单异常、系统升级等理由，通过任何方式发送给您退款链接。请您谨防
                            <span class="color-red">钓鱼链接或诈骗电话</span>！
                        </div>
                    </div>
                </div>

                <div class="item-order item-order-payment" id="error_prompt" style="display:none;"> <!-- 需要隐藏，添加hide类即可 -->
                    <div class="tips-pay">
                        <strong>温馨提示：</strong>
                        <span>如果您有网上支付、银行转账的订单，请您在<strong class="color-red">24</strong>小时内支付 <a href="http://order.dangdang.com/myallorders" id="a_myorder">查看订单</a> </span><br>
                        <span style="padding-left:67px;">您还有 <strong class="color-red">1</strong> 张"待提交"订单 <a href="http://shopping.dangdang.com/shoppingcart/dispart_order.aspx" id="a_submitorder">继续提交</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="footer">
<div class="footer">
	<div class="footer_nav_box">
		<div class="footer_copyright"><span>Copyright (C) 当当网 2004-2014, All Rights Reserved</span><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img" rel="nofollow"><img src="http://img4.dangdang.com/bottom/validate.gif"></a><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span>出版物经营许可证&nbsp;新出发京批字第直0673号</span></div>
	</div>
</div>
</div>
    <div class="foot_tip_ad">广告</div>
    <style>
        .foot_tip_ad { width:40px; height:40px; font:12px/40px "simsun"; text-align:center; color:#fff; background-color:#474747; position:fixed; right:0; bottom:10px;_position:absolute; _bottom:auto;_top:expression(eval(document.documentElement.scrollTop+document.documentElement.clientHeight-this.offsetHeight-(parseInt(this.currentStyle.marginTop,10)||0)-(parseInt(this.currentStyle.marginBottom,10)||0)));}
    </style>


</body>
</html>